# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a8924dcc890da13c511a52e410ca48c43592ac1f5105bbb520f260b7360b560fbe10ac4ab9cf9b0d265ae53b35600408adcc28859365691d38e6fd19171a102

test:
  secret_key_base: 008fb6684927f83087b2e0000a3a3cec36c37c3e0d3581d873b864bad3167ac99e4ca82799b0fb9e5134ff968eac0374cc5caa8285c88f244868a50f099b9586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
